### ISSUE TITLE
Just a quick question on the dynamic routing's similarity measurment

### ISSUE THREAD

**Issue by hohoCode** [gram-ai/capsule-networks#20]
https://github.com/gram-ai/capsule-networks/blob/1a4edd27a0ed73232cb266c85091d712854f3e71/capsule_network.py#L73

I could miss something here, but am just wondering given the original paper, for this line of code on dynamic routing, shouldn't matrix multiplication (e.g. _torch.matmul_) be used to conduct the similarity measurement of the two (_outputs & priors_) matrices? instead of the element-wise product as in the current codes above? 

For example, I know someone else used _torch.matmul_ for this similarity measurement purpose of dynamic routing in this [repo](https://github.com/higgsfield/Capsule-Network-Tutorial/blob/master/Capsule%20Network.ipynb).  

I did not spend lots of time reading everything, but just not sure on this... Thanks for the great implementation!

**Comment by iwasaki-kenta** [comment]
It's more specifically the dot product amongst the two vectors s.t. we enforce priors conditionally on all outputs. If you believe it's wrong though, definitely just comment again and I'll read over the portions of the paper again since it's been awhile.
